FROM node:20-alpine

WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client/tsconfig.json ./
COPY client/tailwind.config.js ./
COPY client/postcss.config.js ./
COPY client/vite.config.ts ./
COPY client/index.html ./
COPY client/src ./src
COPY client/public ./public
COPY shared ../shared

EXPOSE 5173

CMD ["npm", "run", "dev"]