export const content = ["./index.html", "./src/**/*.{ts,tsx}"];
export const theme = {
  extend: {
    fontFamily: {
      playfair: ["'Playfair Display'", "serif"],
      lora: ["Lora", "serif"],
      orbitron: ["Orbitron", "sans-serif"],
    },
    colors: {
      "pong-bg": "#F3F0E8",
      "pong-primary": "#2F3E46",
      "pong-accent": "#C44536",
      "pong-secondary": "#E0A458",
      "pong-highlight": "#AAB7B8",
      "pong-dark-bg": "#1B1B1B",
      "pong-dark-primary": "#AEBABF",
      "pong-dark-accent": "#E05E4B",
      "pong-dark-secondary": "#D1A25F",
      "pong-dark-highlight": "#838E91",
      "pong-gold": "#d4af37",
      "pong-light-bg": "#2c2f40",
      "pong-sport-primary": "#C8A100",
      "pong-sport-accent": "#F6C177",
      "pong-sport-bg": "#1A1C22",
      "pong-sport-surface": "#2C2F36",
      "pong-sport-primary-light": "#A88E28",
      "pong-sport-accent-light": "#B7742C",
      "pong-sport-bg-light": "#F4F1EB",
      "pong-sport-surface-light": "#FFFFFF",
      "pong-sport-muted": "#9FA6B2",
      "pong-footer": "#7391a1",
      "pong-dark-custom": "#0e0e0e",
      "pong-error": "#ef4444",
      "pong-success": "#22c55e",
      "pong-warning": "#f59e0b",
      "pong-info": "#2196F3",
    },
    keyframes: {
      fadeInUp: {
        "0%": { opacity: 0, transform: "translateY(20px)" },
        "100%": { opacity: 1, transform: "translateY(0)" },
      },
      blurIn: {
        "0%": { filter: "blur(4px)", opacity: 0 },
        "100%": { filter: "blur(0)", opacity: 1 },
      },
      backgroundPan: {
        "0%": { backgroundPosition: "0% 0%" },
        "100%": { backgroundPosition: "100% 100%" },
      },
      myFloat: {
        "0%, 100%": { transform: "translateY(0)" },
        "50%": { transform: "translateY(-10px)" },
      },
      myPulse: {
        "0%": { opacity: 1 },
        "50%": { opacity: 0.7 },
      },
      glow: {
        "0%": { boxShadow: "0 0 1px #facc15" },
        "33%": { boxShadow: "0 0 4px #facc15" },
        "66%": { boxShadow: "0 0 6px #facc15" },
        "100%": { boxShadow: "0 0 1px #facc15" },
      },
      slideIn: {
        "0%": { opacity: 0, transform: "translateY(50%)" },
        "100%": { opacity: 1, transform: "translateY(0)" },
      },
      opacity: {
        "0%": { opacity: 0 },
        "100%": { opacity: 1 },
      },
    },
    animation: {
      fadeInUp: "fadeInUp 0.8s ease-out",
      blurIn: "blurIn 0.6s ease-out forwards",
      backgroundPan: "backgroundPan 20s linear infinite",
      myFloat: "myFloat 3s ease-in-out infinite",
      myPulse: "myPulse 1.3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      glow: "glow 2s infinite ease-in-out",
      slideIn: "slideIn 0.5s ease-out forwards",
      opacity: "opacity 0.5s ease-in-out forwards",
    },
  },
};
