FROM node:20-alpine

RUN apk add --no-cache python3 py3-pip make g++ sqlite
RUN pip3 install sqlite-web --break-system-package

WORKDIR /shared
COPY shared/package*.json ./
RUN npm install
COPY shared/tsconfig.json ./
COPY shared/src ./src

WORKDIR /app

COPY server/package*.json ./

RUN npm install /shared
RUN npm ci

COPY server/tsconfig.json ./
COPY server/tsconfig.build.json ./
COPY server/src ./src

RUN mkdir -p uploads/avatars/defaults uploads/avatars/users

EXPOSE 8080
EXPOSE 8081   

CMD ["npm", "run", "dev"]